---
title: "Assignment 8"
author: "Emily K. Power"
date: "`r Sys.Date()`"
output: html_document
---

### Code Reflection  

1. Go through your recent assignments and the posted solutions ([Assignment 6 posted solutions](https://lvash.github.io/BIOL1007A/Assignment-6-dplyr_solutions.html) and [Weekly Assignment 2 solutions](https://lvash.github.io/BIOL1007A/Solutions_Weekly-Assignment-2.html)) - compare your code to the posted code.  

  * Can you run your simulated data function with new values for the means? If not, what do you need to change about your code?
  * Are there differences between the posted code and yours? Did you notice you were missing anything?
  * Make sure you annotate your code using `#` and leave brief descriptions of your thought process.


### Code annotation  

2. I used `dryad` data to reconstruct a publication-quality figure. Copy my code into an Rmd file and annotate what each `ggplot` line of code is doing, including any arguments. You can use a combination of googling and ‘trial/error coding:’ change the arguments/options to visually see how it affects the plot.  

```{r}
## Set up libraries
library(tidyverse)  # load tidyverse library
library(ggthemes)  # load ggthemes library
library(dplyr)


# Data obtained from Veysey Powell and Babbitt 2016: An experimental test of buffer utility as a technique for managing pool-breeding amphibians https://datadryad.org/stash/dataset/doi:10.5061%2Fdryad.547rp

dryadData <- read.table("/Users/emilypower/Desktop/BIOL_1007A/Data/NE_amphibians.csv", header=TRUE, sep=",", stringsAsFactors = TRUE)
  # create table from Veysey Powell and Babbitt 2016 data
  # header=TRUE means variable names are included in first line
  # sep="," sets default separator between values (white space)
  

glimpse(dryadData)  # allows you to see all columns in a data frame
head(dryadData)  # prints first 6 rows of data frame 
table(dryadData$species)  # creates table from dryadData

dryadData$species<-factor(dryadData$species, labels=c("Spotted Salamander", "Wood Frog")) #creating species 'labels' to use for the plot
  # factor() encodes vector as a factor
  # 'labels' argument changes the name of the species labels

#class(dryadData$treatment)
dryadData$treatment <- factor(dryadData$treatment, 
            levels=c("Reference",
                     "100m", "30m"))  # creating treatment 'levels' to use for plot
  # 'levels' argument changes the order of the groups


p<- ggplot(data=dryadData, # create ggplot from dryadData
       aes(x=interaction(wetland, treatment), # sets interaction between wetland and treatment as x variable
           y=count.total.adults, fill=factor(year))) + # sets total adult count as y variable, fill color based on year
geom_bar(position="dodge", stat="identity", color="black") + # creates black bar chart where multiple bars on the same x position are stacked side-to-side; stat="identity" indicates that you will provide y values
  ylab("Number of breeding adults") +  # sets y axis label as 'number of breeding adults'
  xlab("") +  # sets x axis label as nothing
  scale_y_continuous(breaks = c(0,100,200,300,400,500)) +  # adds custom scale numbers to y axis
  scale_x_discrete(labels=c("30 (Ref)", "124 (Ref)", "141 (Ref)", "25 (100m)","39 (100m)","55 (100m)","129 (100m)", "7 (30m)","19 (30m)","20 (30m)","59 (30m)")) +  # adds custom scale labels to x axis
  facet_wrap(~species, nrow=2, strip.position="right") +  # wraps a 1d sequence of panels into 2d (allows you to view 2 species separately)
  theme_few() + scale_fill_grey() +  # sets theme and color gradient of bars
  theme(panel.background = element_rect(fill = 'gray94', color = 'black'), legend.position="top",  legend.title= element_blank(),  axis.title.y = element_text(size=12, face="bold", colour = "black"), strip.text.y = element_text(size = 10, face="bold", colour = "black")) + # sets legend position, colors and text size and type
  guides(fill=guide_legend(nrow=1,byrow=TRUE))  # sets guides for legend

p  # prints bar graph
```

